using System;

namespace Sentirum.Agent.Tools;

/// <summary>
/// Marks a method as a Sentirum tool. Methods decorated with this attribute
/// are picked up by <c>WithTools&lt;TToolset&gt;()</c> on the agent builder
/// and exposed to the LLM as an <see cref="Microsoft.Extensions.AI.AIFunction"/>.
/// </summary>
/// <remarks>
/// <para>
/// The tool's <see cref="Name"/> defaults to the method name (with a trailing
/// <c>Async</c> stripped for tidiness). <see cref="Description"/> is forwarded
/// to the LLM as the function description and should explain what the tool
/// does in plain language.
/// </para>
/// <para>
/// Mark parameters with <see cref="System.ComponentModel.DescriptionAttribute"/>
/// to give the model a hint about what each argument means; the JSON schema
/// generated by <c>AIFunctionFactory</c> picks these descriptions up
/// automatically.
/// </para>
/// </remarks>
[AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = true)]
public sealed class ToolAttribute : Attribute
{
    /// <summary>
    /// Optional override for the tool name. Defaults to the method name with
    /// any trailing <c>Async</c> suffix removed.
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Human-readable description of what the tool does. Forwarded to the
    /// model as the function description.
    /// </summary>
    public string? Description { get; set; }
}
